// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// distanceCalculate
double distanceCalculate(double x1, double y1, double x2, double y2);
RcppExport SEXP _moranfast_distanceCalculate(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< double >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(distanceCalculate(x1, y1, x2, y2));
    return rcpp_result_gen;
END_RCPP
}
// normalize
NumericVector normalize(NumericVector x);
RcppExport SEXP _moranfast_normalize(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize(x));
    return rcpp_result_gen;
END_RCPP
}
// calc_moran
NumericVector calc_moran(NumericVector x, NumericVector c1, NumericVector c2);
RcppExport SEXP _moranfast_calc_moran(SEXP xSEXP, SEXP c1SEXP, SEXP c2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c2(c2SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_moran(x, c1, c2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_moranfast_distanceCalculate", (DL_FUNC) &_moranfast_distanceCalculate, 4},
    {"_moranfast_normalize", (DL_FUNC) &_moranfast_normalize, 1},
    {"_moranfast_calc_moran", (DL_FUNC) &_moranfast_calc_moran, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_moranfast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
